Use std::numeric_limits<double>::max instead of DBL_MAX
Fixes compile error when cfloat wasn't included yet:
```
../3rdParty/multicore_tsne/multicore_tsne/vptree.h: In member function ‘void VpTree<T, distance>::search(const T&, int, std::vector<T>*, std::vector<double>*)’:
../3rdParty/multicore_tsne/multicore_tsne/vptree.h:103:22: error: ‘DBL_MAX’ was not declared in this scope
  103 |         double tau = DBL_MAX;
      |                      ^~~~~~~
../3rdParty/multicore_tsne/multicore_tsne/vptree.h:17:1: note: ‘DBL_MAX’ is defined in header ‘<cfloat>’; did you forget to ‘#include <cfloat>’?
```