Assorted cleanups (#83)
* Fix typo in header include guard

* Make tsne_multicore a static library

This allows easier consumption of the library from CMake projects.
We can now just link to it directly, instead of having to rely
on dlopen at runtime.

* Modernize CMake build script

Add tsne_multicore::tsne_multicore alias target and setup the
target include directories to allow easier consumption of this
library - just link to the alias target.

Also don't use GLOB but isntead list the sources directly. This
is best-practice, globing woudl fail to pick up new files that
get added without force-running cmake manually.

* Link against OpenMP::OpenMP_CXX target

Now that we depend on CMake 3.9 we can simplify OpenMP consumption.
Just link against the alias target which will pull everything needed
in. See also:
https://cliutils.gitlab.io/modern-cmake/chapters/packages/OpenMP.html

* Do not link against libc++ and libstdc++

This should not be needed on macOS and hints at an issue at the
consumer side. Most notably note that it is usually a very bad
idea to link libc++ _and_ libstdc++ into the same TU.

Keep libm, but use target_link_libraries for that purpose.

* Remove useless CMAKE_MODULE_PATH

There is no cmake subfolder, so this is not needed.

* Modernize cmake: use target properties

Leverage CMake to set -fPIC in a platform agnostic way and
set target_compile_options with generator expressions. Do not
override -O, just use the default of Release or RelWithDebInfo.

* cmake: make it possible to install multicore_tsne

This allows the library to be consumed via find_package from another
project. The CMake script now creates a Config.cmake file which will
then be found which makes the tsne_multicore::tsne_multicore target
available, together with its interface variables, most notably the
include path.

* Forward-declare DataPoint from vptree in tsne.h to fix compile error

Fixes the following error when one is just including tsne.h.
Generally it's considered best-practice to have headers be
fully self-contained.

```
../3rdParty/multicore_tsne/multicore_tsne/tsne.h:18:49: error: ‘DataPoint’ does not name a type
   18 | template <class treeT, double (*dist_fn)( const DataPoint&, const DataPoint&)>
      |                                                 ^~~~~~~~~
```

* Use std::numeric_limits<double>::max instead of DBL_MAX

Fixes compile error when cfloat wasn't included yet:
```
../3rdParty/multicore_tsne/multicore_tsne/vptree.h: In member function ‘void VpTree<T, distance>::search(const T&, int, std::vector<T>*, std::vector<double>*)’:
../3rdParty/multicore_tsne/multicore_tsne/vptree.h:103:22: error: ‘DBL_MAX’ was not declared in this scope
  103 |         double tau = DBL_MAX;
      |                      ^~~~~~~
../3rdParty/multicore_tsne/multicore_tsne/vptree.h:17:1: note: ‘DBL_MAX’ is defined in header ‘<cfloat>’; did you forget to ‘#include <cfloat>’?
```

* Inline euclidean_distance_squared

Fixes linker error about ODR violation when linking:
```
ld.lld: error: duplicate symbol: euclidean_distance_squared(DataPoint const&, DataPoint const&)
>>> defined at vptree.h:62 (../3rdParty/multicore_tsne/multicore_tsne/vptree.h:62)
>>>            KDAB/features/CMakeFiles/QiTissue_Features.dir/tsnedatagenerator.cpp.o:(euclidean_distance_squared(DataPoint const&, DataPoint const&))
>>> defined at vptree.h:62 (../3rdParty/multicore_tsne/multicore_tsne/vptree.h:62)
>>>            tsne.cpp.o:(.text+0x4B) in archive lib/libtsne_multicore.a
```

* Initialize variable to prevent compiler warning

Fixes:
```
../3rdParty/multicore_tsne/multicore_tsne/tsne.cpp:431:22: warning: ‘sum_P’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  431 |             cur_P[m] /= sum_P;
../3rdParty/multicore_tsne/multicore_tsne/tsne.cpp:384:30: note: ‘sum_P’ was declared here
  384 |         int iter = 0; double sum_P;
      |                              ^~~~~
```

* Do not call exit() when memory allocation fails

When tsne_multicore is used as a library in a larger application,
one does not want to kill the whole application when tsne fails to
allocate some memory. Handle this more gracefully by just returning
when an error occurs.

* Don't crash when running on all-zero data

In such a case the code would try a division by zero which would
then crash.